const API_ENDPOINTS = {
  AUTH: {
    REGISTER: "/auth/register",
    VERIFY_OTP: "/auth/verify-otp",
    RESEND_OTP: "/auth/resend-otp",
    GOOGLE_LOGIN: "/auth/google",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_FORGOT_PASSWORD_OTP: "/auth/verify-forgot-password-otp",
    RESET_PASSWORD: "/auth/reset-password",
    USER_INFO: "/users/user-info",
    UPDATE_PROFILE: "/users/update-profile",
    UPLOAD_AVATAR: "/users/upload-avatar",
  },
  TUTORS: {
    REGISTER: "/tutors/register",
    UPLOAD_DOCUMENT: "/tutors/upload-document",
    GET_PROFILE: "/tutors/profile",
    GET_ACTIVE: "/tutors/active",
    GET_TOP: "/tutors/top",
    GET_TOP_THIS_MONTH: "/tutors/top/month/current",
    GET_NEW: "/tutors/new",
    SEARCH: "/tutors/search",
    GET_BY_ID: (id) => `/tutors/${id}`,
    PROFILE_CHANGE_REQUEST: "/tutors/profile/change-request",
  },
  ADMIN: {
    DASHBOARD_STATS: "/admin/tutors/stats",
    TUTORS_PENDING: "/admin/tutors/pending",
    TUTOR_APPROVE: (id) => `/admin/tutors/${id}/approve`,
    TUTOR_REJECT: (id) => `/admin/tutors/${id}/reject`,
    USERS: "/admin/users",
    USER_UPDATE: (id) => `/admin/users/${id}`,
    USER_STATUS: (id) => `/admin/users/${id}/status`,
    USER_DELETE: (id) => `/admin/users/${id}`,
    CLASS_APPLICATIONS: "/admin/class-applications",
    CLASS_APPLICATIONS_STATS: "/admin/class-applications/stats",
    CLASS_APPLICATION_APPROVE: (id) => `/admin/class-applications/${id}/approve`,
    CLASS_APPLICATION_REJECT: (id) => `/admin/class-applications/${id}/reject`,
    CLASSES: "/admin/classes",
    CLASS_DELETE: (id) => `/admin/classes/${id}`,
    TRASH_COUNTS: "/admin/trash/counts",
    TRASH_LIST: (type) => `/admin/trash/${type}`,
    TRASH_RESTORE: (type, id) => `/admin/trash/${type}/${id}/restore`,
    TRASH_PURGE: (type, id) => `/admin/trash/${type}/${id}`,
    PROFILE_CHANGES: "/admin/profile-changes",
    PROFILE_CHANGE_APPROVE: (id) => `/admin/profile-changes/${id}/approve`,
    PROFILE_CHANGE_REJECT: (id) => `/admin/profile-changes/${id}/reject`,
    APPLICATION_CANCELLATIONS: "/admin/application-cancellations",
    CANCELLATION_APPROVE: (id) => `/admin/application-cancellations/${id}/approve`,
    CANCELLATION_REJECT: (id) => `/admin/application-cancellations/${id}/reject`,
    REVIEW_TUTORS: "/admin/reviews/tutors",
    REVIEW_TUTOR_REVIEWS: (tutorId) => `/admin/reviews/tutors/${tutorId}`,
    REVIEW_DELETE: (id) => `/admin/reviews/${id}`,
  },
  LOCATIONS: {
    PROVINCES: "/locations/provinces",
    DISTRICTS: (provinceCode) => `/locations/provinces/${provinceCode}/districts`,
    SCHOOLS: "/locations/schools",
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_READ: (id) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  LOOKUPS: {
    ALL: "/lookups/all",
    BY_TYPE: (type) => `/lookups/type/${type}`,
    DISTRICTS_BY_PROVINCE: (province) => `/lookups/districts/${province}`,
  },
  SUBJECTS: {
    LIST: "/subjects",
    ADMIN_LIST: "/subjects/admin",
    CREATE: "/subjects",
    UPDATE: (id) => `/subjects/${id}`,
  },
  PROMOS: {
    VALIDATE: "/promos/validate",
    MINE: "/promos/mine",
    LIST: "/promos",
    CREATE: "/promos",
    UPDATE: (id) => `/promos/${id}`,
    DELETE: (id) => `/promos/${id}`,
  },
  CLASSES: {
    QUOTE: "/classes/quote",
    CREATE: "/classes",
    UPDATE: (id) => `/classes/${id}`,
    DELETE: (id) => `/classes/${id}`,
    LIST: "/classes",
    SUBJECTS: "/classes/subjects",
    PRICING_CONFIG: "/classes/pricing-config",
    DETAIL: (id) => `/classes/${id}`,
    MINE: "/classes/mine",
    FEED: "/classes/feed",
    MY_POSTS: "/classes/my-posts",
    APPLY: (id) => `/classes/${id}/apply`,
    APPLICANTS: (id) => `/classes/${id}/applicants`,
    SELECT_APPLICANT: (id, applicationId) => `/classes/${id}/applicants/${applicationId}/select`,
    CANCEL_APPLICATION: (id) => `/classes/applications/${id}/cancel`,
    COMPLETE: (id) => `/classes/${id}/complete`,
    // Mời gia sư trực tiếp
    INVITE: "/classes/invite",
    INVITATIONS: "/classes/invitations",
    INVITATION_ACCEPT: (applicationId) => `/classes/invitations/${applicationId}/accept`,
    INVITATION_DECLINE: (applicationId) => `/classes/invitations/${applicationId}/decline`,
  },
  REVIEWS: {
    CREATE: "/reviews",
    BY_TUTOR: (tutorId) => `/reviews/tutor/${tutorId}`,
    REPLY: (id) => `/reviews/${id}/reply`,
  },
  CHAT: {
    // Gia sư — cuộc trò chuyện duy nhất với admin
    MY_CONVERSATION: "/chat/my-conversation",
    MY_UNREAD_COUNT: "/chat/my-conversation/unread-count",
    MY_SEND: "/chat/my-conversation/messages",
    MY_SEND_IMAGE: "/chat/my-conversation/images",
    MY_READ: "/chat/my-conversation/read",
    // Admin
    CONVERSATIONS: "/chat/conversations",
    ADMIN_UNREAD_COUNT: "/chat/conversations/unread-count",
    CONVERSATION_MESSAGES: (id) => `/chat/conversations/${id}/messages`,
    CONVERSATION_SEND: (id) => `/chat/conversations/${id}/messages`,
    CONVERSATION_SEND_IMAGE: (id) => `/chat/conversations/${id}/images`,
    CONVERSATION_READ: (id) => `/chat/conversations/${id}/read`,
  },
};

export default API_ENDPOINTS;
