const API_ENDPOINTS = {
  AUTH: {
    REGISTER: "/auth/register",
    VERIFY_OTP: "/auth/verify-otp",
    RESEND_OTP: "/auth/resend-otp",
    GOOGLE_LOGIN: "/auth/google",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_FORGOT_PASSWORD_OTP: "/auth/verify-forgot-password-otp",
    RESET_PASSWORD: "/auth/reset-password",
    USER_INFO: "/users/user-info",
    UPDATE_PROFILE: "/users/update-profile",
    UPLOAD_AVATAR: "/users/upload-avatar",
  },
  TUTORS: {
    REGISTER: "/tutors/register",
    GET_PROFILE: "/tutors/profile",
    GET_ACTIVE: "/tutors/active",
    GET_TOP: "/tutors/top",
    GET_TOP_THIS_MONTH: "/tutors/top/month/current",
    GET_NEW: "/tutors/new",
    SEARCH: "/tutors/search",
    GET_BY_ID: (id) => `/tutors/${id}`,
  },
  ADMIN: {
    DASHBOARD_STATS: "/admin/tutors/stats",
    TUTORS_PENDING: "/admin/tutors/pending",
    TUTOR_APPROVE: (id) => `/admin/tutors/${id}/approve`,
    TUTOR_REJECT: (id) => `/admin/tutors/${id}/reject`,
    USERS: "/admin/users",
    USER_UPDATE: (id) => `/admin/users/${id}`,
    USER_STATUS: (id) => `/admin/users/${id}/status`,
    USER_DELETE: (id) => `/admin/users/${id}`,
    CLASS_APPLICATIONS: "/admin/class-applications",
    CLASS_APPLICATIONS_STATS: "/admin/class-applications/stats",
    CLASS_APPLICATION_APPROVE: (id) => `/admin/class-applications/${id}/approve`,
    CLASS_APPLICATION_REJECT: (id) => `/admin/class-applications/${id}/reject`,
  },
  LOCATIONS: {
    PROVINCES: "/locations/provinces",
    DISTRICTS: (provinceCode) => `/locations/provinces/${provinceCode}/districts`,
    SCHOOLS: "/locations/schools",
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_READ: (id) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  LOOKUPS: {
    ALL: "/lookups/all",
    BY_TYPE: (type) => `/lookups/type/${type}`,
    DISTRICTS_BY_PROVINCE: (province) => `/lookups/districts/${province}`,
  },
  CLASSES: {
    QUOTE: "/classes/quote",
    CREATE: "/classes",
    LIST: "/classes",
    SUBJECTS: "/classes/subjects",
    PRICING_CONFIG: "/classes/pricing-config",
    DETAIL: (id) => `/classes/${id}`,
    MINE: "/classes/mine",
    APPLY: (id) => `/classes/${id}/apply`,
  },
};

export default API_ENDPOINTS;
